### ISSUE TITLE
can't be compiled

### ISSUE THREAD

**Issue by terryshenzhen** [mavroprovato/qt-scintilla-editor#1]
down load  scintilla, and   compile under ubuntu, it tell me cant,t find string_view;  after upgrede thr gCC version and change .pro, it success finally,
but... this project can recorgnize the dll .
I waste some time to  compile,but still failed

**Comment by mavroprovato** [comment]
Hi thanks for reporting the issue!

As you can see for yourself it's been seven years since I last worked on the project. Since then, it seems that the scintilla component requires C++17 in order to build correctly.

I'll try to fix the build procedure and improve the documentation so that the project is easier to build and I'll get back to you

**Comment by mavroprovato** [comment]
@terryshenzhen I updated the master branch, now it should be ok. Please check
